import re
import logging
from typing import List, Dict, Any, Optional

from generator.prompt_builder import build_prompt
from generator.answer_generator import generate_answer
from generator.citation_generator import add_citations
from generator.confidence_estimator import calculate_confidence

# Initialize logger
logger = logging.getLogger(__name__)

class GroundedResponse:
    """
    A structured data wrapper representing a publication-level grounded clinical response.
    
    This class wraps the text answer, parsed components, citations, confidence scores,
    and metadata. It supports future agentic retrieval states or session-based memory integrations.
    """
    def __init__(
        self,
        raw_output: str,
        answer: str,
        clinical_explanation: str,
        key_points: List[str],
        references: List[Dict[str, Any]],
        confidence: float,
        is_sufficient: bool
    ):
        self.raw_output = raw_output
        self.answer = answer
        self.clinical_explanation = clinical_explanation
        self.key_points = key_points
        self.references = references
        self.confidence = confidence
        self.is_sufficient = is_sufficient
        
        # Future-proofing attributes (agentic retrieval & memory placeholders)
        self.retrieval_history: List[Dict[str, Any]] = []
        self.memory_context: Optional[Dict[str, Any]] = None

    def __str__(self) -> str:
        """
        Returns a beautifully formatted string representation of the grounded QA output.
        """
        if not self.is_sufficient:
            return "Insufficient evidence available in retrieved documents."
            
        output = ""
        output += "Clinical Answer:\n"
        output += f"{self.answer}\n\n"
        output += "Clinical Explanation:\n"
        output += f"{self.clinical_explanation}\n\n"
        output += "Key Points:\n"
        for p in self.key_points:
            output += f"- {p}\n"
            
        output += "\nReferences\n"
        seen = set()
        for ref in self.references:
            book = ref.get("book")
            chapter = ref.get("chapter")
            ref_key = (book, chapter)
            if ref_key not in seen:
                seen.add(ref_key)
                output += f"\n{book}\n"
                if chapter is not None:
                    output += f"Chapter {chapter}\n"
                    
        output += f"\nSystem Confidence Estimate: {self.confidence:.2f}\n"
        return output

    @property
    def structured_data(self) -> Dict[str, Any]:
        """
        Formats the internal state into the standardized schema for later evaluation.
        """
        return {
            "answer": self.answer,
            "clinical_explanation": self.clinical_explanation,
            "key_points": self.key_points,
            "references": self.references,
            "confidence": self.confidence,
            "is_sufficient": self.is_sufficient
        }


def parse_model_output(output: str) -> tuple:
    """
    Parses structured sections from the clinical model response using header parsing.
    
    Args:
        output: Raw output string generated by the LLM.
        
    Returns:
        A tuple of (answer, clinical_explanation, key_points)
    """
    # Clean output whitespace
    output = output.strip()
    
    # 1. Handle insufficiency rule match
    if "Insufficient evidence available in retrieved documents." in output:
        return "Insufficient evidence available in retrieved documents.", "", []
        
    answer = ""
    explanation = ""
    key_points = []
    
    # 2. Extract [ANSWER] block
    answer_match = re.search(
        r'\[ANSWER\](.*?)(?=\[CLINICAL EXPLANATION\]|\[KEY POINTS\]|$)', 
        output, 
        re.DOTALL | re.IGNORECASE
    )
    if answer_match:
        answer = answer_match.group(1).strip()
        
    # 3. Extract [CLINICAL EXPLANATION] block
    explanation_match = re.search(
        r'\[CLINICAL EXPLANATION\](.*?)(?=\[KEY POINTS\]|\[ANSWER\]|$)', 
        output, 
        re.DOTALL | re.IGNORECASE
    )
    if explanation_match:
        explanation = explanation_match.group(1).strip()
        
    # 4. Extract [KEY POINTS] block
    key_points_match = re.search(
        r'\[KEY POINTS\](.*?)$', 
        output, 
        re.DOTALL | re.IGNORECASE
    )
    if key_points_match:
        points_text = key_points_match.group(1).strip()
        # Find all bulleted items
        raw_items = re.findall(r'(?:^|\n)\s*[-*]\s*(.*?)(?=\n\s*[-*]|$)', points_text)
        key_points = [p.strip() for p in raw_items if p.strip()]
        
    # 5. Parsing fallback (safety net)
    if not answer and not explanation:
        # If no tags matched, fall back to returning raw output under answer
        answer = output
        
    return answer, explanation, key_points


def grounded_generation(query: str, retrieved_documents: List[Dict[str, Any]]) -> GroundedResponse:
    """
    Executes the publication-level grounded generation pipeline.
    
    Pipeline Architecture:
      1. Confidence Estimation: Compute query-evidence retrieval similarity metrics.
      2. Prompt Builder: Inject strictly grounded prompt instructions.
      3. Answer Generator: Execute resource-optimized local CPU generation.
      4. Grounding Check & Parse: Standardize headers and prevent hallucination.
      5. Citation Generator: Map evidence references to final formatted section.
      
    Args:
        query: The medical research or patient diagnosis question.
        retrieved_documents: Context literature chunks.
        
    Returns:
        A GroundedResponse instance encapsulating structured answers and metadata.
    """
    logger.info("Starting grounded generation pipeline execution...")
    
    # 1. Run Confidence Estimation on retrieval results
    confidence_result = calculate_confidence(retrieved_documents)
    confidence = confidence_result.get("confidence", 0.0)
    
    # 2. Build the structured publication-grade medical prompt (limit to top 3 documents to fit CPU context & latency limits)
    prompt_docs = retrieved_documents[:3]
    prompt = build_prompt(query, prompt_docs)
    
    # 3. Call local model inference on CPU
    raw_output = generate_answer(prompt)
    
    # 4. Apply hallucination parsing & structure matching
    answer, clinical_explanation, key_points = parse_model_output(raw_output)
    
    # 5. Check if sufficiency fallback was triggered
    is_sufficient = True
    if answer == "Insufficient evidence available in retrieved documents.":
        is_sufficient = False
        
    # 6. Build the references metadata list (only referencing documents actually included in context)
    references = []
    seen_refs = set()
    for doc in prompt_docs:
        book = doc.get("book")
        chapter = doc.get("chapter")
        if book:
            ref_key = (str(book).strip(), chapter)
            if ref_key not in seen_refs:
                seen_refs.add(ref_key)
                references.append({"book": book, "chapter": chapter})
                
    # 7. Construct final GroundedResponse encapsulation
    response = GroundedResponse(
        raw_output=raw_output,
        answer=answer,
        clinical_explanation=clinical_explanation,
        key_points=key_points,
        references=references,
        confidence=confidence,
        is_sufficient=is_sufficient
    )
    
    logger.info("Pipeline execution complete. GroundedResponse initialized.")
    return response